//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tshirt.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableTshirt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tableTshirt()
        {
            this.tableCommande = new HashSet<tableCommande>();
        }
    
        public int IdTshirt { get; set; }
        public string taille { get; set; }
        public string couleur { get; set; }
        public string prix { get; set; }
        public string img { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tableCommande> tableCommande { get; set; }
    }
}
