//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tshirt.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableCommande
    {
        public int IdCmd { get; set; }
        public Nullable<int> IdCmdTshirt { get; set; }
        public string etat { get; set; }
        public Nullable<int> IdCmdClt { get; set; }
    
        public virtual tableClient tableClient { get; set; }
        public virtual tableTshirt tableTshirt { get; set; }
    }
}
